# name字段是 workflow 的名称。如果省略该字段，默认为当前 workflow 的文件名。
# name: GitHub Action Demo

# on字段指定触发 workflow 的条件，通常是某些事件。
# 只有main分支发生push事件时，才会触发 workflow。
# on:
#   push:
#     branches:
#       - main

# jobs.<job_id>.name
# workflow 文件的主体是jobs字段，表示要执行的一项或多项任务。
# jobs字段里面，需要写出每一项任务的job_id，具体名称自定义
# jobs:
#   my_first_job:
#     name: My first job
#   my_second_job:
#     name: My second job

# jobs.<job_id>.needs
# needs字段指定当前任务的依赖关系，即运行顺序。

# jobs.<job_id>.runs-on
# runs-on字段指定运行所需要的虚拟机环境。它是必填字段。
# runs-on: ubuntu-latest

# jobs.<job_id>.steps
# steps字段指定每个 Job 的运行步骤，可以包含一个或多个步骤。每个步骤都可以指定以下三个字段。
# jobs.<job_id>.steps.name：步骤名称。
# jobs.<job_id>.steps.run：该步骤运行的命令或者 action。
# jobs.<job_id>.steps.env：该步骤所需的环境变量。

name: GitHub Action Demo
on:
  push:
    branches:
      - main


jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
    - name: Print a greeting
      env:
        MY_VAR: Hi there! My name is
        FIRST_NAME: Kylin
        MIDDLE_NAME: And
        LAST_NAME: My girlfriend is lsy
      run: |
        echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.
